#!/usr/bin/env python3
"""Summary Generator for Clean Chassis GitHub Actions.

Runs incremental audit checks (syntax compilation, unit test discovery,
security scan with Bandit) and produces:
- summary.md: Visual Markdown report for PR comments and $GITHUB_STEP_SUMMARY.
- artifacts/audit_summary.json: Metrics data for PR renamer and checklist updater.
"""

import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Tuple

BASE_DIR = Path(__file__).resolve().parent.parent
ARTIFACTS_DIR = BASE_DIR / "artifacts"
ARTIFACTS_DIR.mkdir(exist_ok=True)


def run_command(cmd: list[str]) -> Tuple[int, str]:
    """Runs a shell command and returns (exit_code, output_text)."""
    try:
        res = subprocess.run(cmd, cwd=str(BASE_DIR), capture_output=True, text=True, check=False)
        output = (res.stdout + "\n" + res.stderr).strip()
        return res.returncode, output
    except Exception as e:
        return 1, str(e)


def _check_syntax() -> Tuple[str, str, int]:
    """Compiles all existing Python files to check for syntax errors."""
    ignore_parts = (".venv", "venv", "__pycache__", ".git", "build", "dist")
    py_files = [
        str(p) for p in BASE_DIR.rglob("*.py") if not any(part in p.parts for part in ignore_parts)
    ]
    if not py_files:
        return "✅ PASSED", "No Python files found.", 0

    code, out = run_command([sys.executable, "-m", "py_compile", *py_files])
    status = "✅ PASSED" if code == 0 else "❌ FAILED"
    return status, out, len(py_files)


def _check_unit_tests() -> Tuple[str, str, int, int]:
    """Runs existing unit tests and parses pass/total counts."""
    test_files = list((BASE_DIR / "tests").rglob("test_*.py"))
    if not test_files:
        return "✅ PASSED", "Ran 0 tests in 0.000s\n\nOK", 0, 0

    code, out = run_command(
        [sys.executable, "-m", "unittest", "discover", "-s", "tests", "-p", "test_*.py"]
    )
    status = "✅ PASSED" if code == 0 else "❌ FAILED"

    total = 0
    passed = 0
    for line in out.splitlines():
        if "Ran " in line and "tests in" in line:
            try:
                total = int(line.split("Ran ")[1].split(" tests")[0])
                passed = total if code == 0 else 0
            except Exception:
                pass
    return status, out, passed, total


def _build_markdown(
    overall_status: str,
    timestamp: str,
    compile_status: str,
    py_count: int,
    test_status: str,
    passed_tests: int,
    total_tests: int,
    sec_status: str,
    test_out: str,
) -> str:
    """Builds the comprehensive markdown report text."""
    md = [
        "# 🛡️ Clean Chassis — Audit & Quality Gate Report",
        f"**Overall Status**: {overall_status}  ",
        f"**Execution Timestamp**: `{timestamp}`  \n",
        "## 📊 Summary Overview",
        "| Metric | Status | Details |",
        "| :--- | :--- | :--- |",
        f"| ⚡ **Python 3.10 Syntax** | {compile_status} | Verified {py_count} file(s) |",
        f"| 🧪 **Test Suites** | {test_status} | {passed_tests}/{total_tests} test(s) |",
        f"| 🔒 **Security Audit (Bandit)** | {sec_status} | Codebase vulnerability scan |",
        "\n## 🔍 Test Execution Log\n",
        "<details><summary><b>View Test Execution Details</b></summary>\n",
        "```text",
        test_out,
        "```",
        "</details>\n",
        "---\n*Automated audit report generated by Clean Chassis.*",
    ]
    return "\n".join(md)


def main() -> None:
    """Executes the audit suite and generates markdown/json reports."""
    compile_status, _, py_count = _check_syntax()
    test_status, test_out, passed_tests, total_tests = _check_unit_tests()

    sec_code, _ = run_command([sys.executable, "-m", "bandit", "-r", "src", "scripts", "-q"])
    sec_status = "✅ PASSED" if sec_code == 0 else "⚠️ REVIEW"

    overall_passed = compile_status == "✅ PASSED" and test_status == "✅ PASSED"
    overall_status = "✅ AUDIT 100% PASSED" if overall_passed else "⚠️ AUDIT FAILED"
    timestamp = datetime.now().strftime("%d/%m/%Y %H:%M:%S")

    summary_text = _build_markdown(
        overall_status,
        timestamp,
        compile_status,
        py_count,
        test_status,
        passed_tests,
        total_tests,
        sec_status,
        test_out,
    )

    with open(BASE_DIR / "summary.md", "w", encoding="utf-8") as f:
        f.write(summary_text)

    metrics = {
        "timestamp": timestamp,
        "overall_passed": overall_passed,
        "py_files_count": py_count,
        "passed_tests": passed_tests,
        "total_tests": total_tests,
    }

    with open(ARTIFACTS_DIR / "audit_summary.json", "w", encoding="utf-8") as f:
        json.dump(metrics, f, indent=2)

    print("✔ Audit summary and metrics JSON generated successfully.")


if __name__ == "__main__":
    main()
